// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydkxshkefoqsmpbsftqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlka3hzaGtlZm9xc21wYnNmdHFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2OTE1MTIsImV4cCI6MjA1OTI2NzUxMn0.UwLReakHEd4zXEIUdD2G29fM6_Dr7NzTy1hY8-eKTxU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);